lesson_18
Yorickov/test-guru pull request #23
Opened 2020-01-13 20:46 UTC by Yorickov

2020-01-14 08:47 UTC, BubuntuClu requested changes

2020-01-14 08:47 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    time_left = params[:value]
сюда параметром можно подставить что угодно и так манипулировать временем.
надо сделать проверку на фронте, которая будет отсчитывать время(если пользователь засиделся на странице) и потом переидывать на страницу результатов. и так же надо сделать проверку времени на бэке, если вдруг джс отключат.

не вижу миграции на добавление времени в тест

2020-01-14 09:05 UTC, Yorickov commented on app/controllers/test_passages_controller.rb
> +    time_left = params[:value]
https://github.com/Yorickov/test-guru/blob/master/db/migrate/20191230165511_add_columns_to_tests_and_test_passages.rb

2020-01-14 11:49 UTC, Yorickov commented on app/controllers/test_passages_controller.rb
> +    time_left = params[:value]
что-то я перемудрил с таймером, насоздавав кучу лишних проблем, переделаю все.

2020-01-14 11:53 UTC, Yorickov commented on app/controllers/test_passages_controller.rb
> +    time_left = params[:value]
хотя манипулировать  ?value там вряд ли удастся, но все равно переделаю

2020-01-15 08:34 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    time_left = params[:value]
а почему в этом ПР нет этого файла?

2020-01-15 08:36 UTC, BubuntuClu approved these changes

2020-01-15 08:36 UTC, BubuntuClu commented on app/javascript/utilities/timer.js
> +      location.href = url + '?timeoff=true';
не надо передавать параметры. на странице результата, он же может убрать этот параметр и перегрузить страницу, тогда результат же другой будет

2020-01-15 08:36 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    if params[:timeoff]
тут просто следует еще раз проверить не вышло ли время

2020-01-15 14:22 UTC, merged